language: node_js
node_js:
  - '8'

before_install:
  - npm install -g yarn

install:
  - yarn install

script:
  - yarn build
  - yarn lint
  - yarn test

after_script:
  - "cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"

cache: yarn
